version: "3.0"

services:
  Persistence:
    build:
      context: ./FileIO/
      dockerfile: ./Dockerfile
    ports:
      - 8081:8081
    stdin_open: true
    container_name: persistence_service
  shutthebox:
    build:
      context: ./
      dockerfile: ./Dockerfile
    stdin_open: true
    container_name: root_service
    depends_on:
      - field
    environment:
      - DISPLAY=host.docker.internal:0